### ISSUE TITLE
Type `PositionLike` no longer exported

### ISSUE THREAD

**Issue by Methuselah96** [wooorm/unist-util-position#10]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

unist-util-position@4,0.4

### Steps to reproduce

Add `react-markdown` to a TS project with `skipLibCheck` set to `false`.

### Expected behavior

No type errors in the declaration files.

### Actual behavior

```
ERROR in node_modules/mdast-util-to-hast/lib/index.d.ts:25:58
TS2694: Namespace '"node_modules/unist-util-position/index"' has no exported member 'PositionLike'.
    23 | export type Element = import('hast').Element
    24 | export type Content = import('hast').ElementContent
  > 25 | export type PositionLike = import('unist-util-position').PositionLike
       |                                                          ^^^^^^^^^^^^
    26 | export type EmbeddedHastFields = {
    27 |   /**
    28 |    * Defines the tag name of an element.
```

### Affected runtime and version

N/A

**Comment by wooorm** [comment]
thanks for the report!
