### ISSUE TITLE
Bundled type definitions are faulty

### ISSUE THREAD

**Issue by d-fischer** [wooorm/unist-util-position#7]
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

Affected packages and versions: 4.0.0

### Steps to reproduce

```sh
mkdir bug
cd bug
yarn init -y
yarn add typescript unist-util-position @types/unist
yarn tsc --init
echo "import { pointStart } from 'unist-util-position';" > index.ts
yarn tsc index.ts
```

### Expected behavior

Compiles with no errors.

### Actual behavior
```
$ yarn tsc index.ts
yarn run v1.22.4
$ /home/daniel/Projekte/bug/node_modules/.bin/tsc index.ts
node_modules/unist-util-position/index.d.ts:16:11 - error TS2304: Cannot find name 'type'.

16   export {type as displayName}
             ~~~~


Found 1 error.
```

**Comment by wooorm** [comment]
thanks @d-fischer, released!
